#!/usr/bin/python
# Copyright 2011 David Steele <daves@users.sourceforge.net>
# This file is part of gnome-gmail
# Available under the terms of the GNU General Public License version 2 or later


""" pretend to be the evolution mail client, so that Open Office will deign
to call. Pass the mailto URL to the preferred gnome mail handler. """

import os
import sys

os.system( 'xdg-open "%s"' % sys.argv[1] )
