.\" Copyright 2011-2014 David Steele <dsteele@gmail.com>
.\" This file is part of gnome-gmail
.\" Available under the terms of the GNU General Public License version 2 or later
.TH gnome-gmail 1 "7 June 2015" Linux "User Commands"
.SH NAME
gnome-gmail \- Integrate GMail into the GNOME desktop
.SH SYNOPSIS
\fBgnome-gmail\fP [\fI<mailto-URL>\fP]
.SH DESCRIPTION
The \fBgnome-gmail\fP script opens a GMail page on the default web browser, with a message composed according
to the supplied RFC2368 \fImailto:\fP URL. This script is used to support GMail as a GNOME Preferred Application for email.
.SH OPTIONS
A \fImailto:\fP URL. The 'To', 'CC', 'BCC', 'Subject', and 'Body' fields are supported. If the argument is
not well formed, it is assumed to be the recipient. If no argument is supplied, a default GMail page is opened.
.SH FILES
~/.config/gnome-gmail/gnome-gmail.conf - Configuration file
.SH BUGS
No known bugs.
.SH AUTHOR
David Steele (dsteele@gmail.com)
