#!/bin/sh

export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/gnome-gmail.schemas > /dev/null

if [ -f /usr/share/icons/hicolor/icon-theme.cache ]; then \
  gtk-update-icon-cache -f /usr/share/icons/hicolor >/dev/null 2>&1; \
fi

#gconftool-2 --set --type=string /desktop/gnome/url-handlers/mailto/command "gnome-gmail %s"
#gconftool-2 --set --type=bool /desktop/gnome/url-handlers/mailto/enabled true
#gconftool-2 --set --type=bool /desktop/gnome/url-handlers/mailto/needs_terminal false

update-gconf-defaults
