#!/usr/bin/python -tt
#
# Copyright 2011 David Steele <daves@users.sourceforge.net>
# This file is part of gnome-gmail
# Available under the terms of the GNU General Public License version 2 or later
#

import gio


    # set this app as the GNOME mailto handler, new-style
[ app.set_as_default_for_type( "x-scheme-handler/mailto" ) 
      for app in gio.app_info_get_all_for_type( "x-scheme-handler/mailto" )
      if app.get_name() == "Gnome Gmail" ]

