.\" Copyright 2011 David Steele <daves@users.sourceforge.net>
.\" This file is part of gnome-gmail
.\" Available under the terms of the GNU General Public License version 2 or later
.TH setOOmailer 1 "12 February 2011" Linux "User Commands"
.SH NAME
setOOmailer \- Configure LibreOffice and Open Office to use the GNOME preferred email application
.SH SYNOPSIS
\fBsetOOmailer\fP
.SH DESCRIPTION
This script will attempt to set the current user's LibreOffice and Open Office configurations to use the GNOME preferred
email application for "Send File" functions. It is intended to run at login.
.SH OPTIONS
None
.SH SEE ALSO
gnome-gmail(1)
.SH BUGS
The script does not report errors.
.SH AUTHOR
David Steele (daves@users.sourceforge.net)
